### PR TITLE
allow to_gbq without datasets.create permissions

### LINKED ISSUE #73: allow to_gbq without datasets.create permissions
Currently, due to https://github.com/coiled/dask-bigquery/blob/b6d5b04e544350b2dd46e10221844d56024e92ba/dask_bigquery/core.py#L312, you cannot execute to_gbq in the situation where a dataset already exists but you do not have datasets.create permissions. Perhaps it would make sense to try `get_dataset` first, and if that doesn't work, call `create_dataset`. That would handle this situation I believe.

### PR DESCRIPTION
**Pull request by bolliger32**
Fixes #73

### CODE REVIEW

**Comment by ncclementi** [comment]
@j-bennet I'm realizing that since it's a PR from a fork, CI won't run because of the secrets issue that GHAS + PR has. What would be the best course of action here?

**Comment by j-bennet** [comment]
@ncclementi give @bolliger32 push access to this repo?

**Comment by ncclementi** [comment]
@bolliger32 You should have received an invite to the repo, and have push access. Would you mind pushing these changes to a branch instead of the fork so we can trigger CI?

Apologies for the delay

**Comment by bolliger32** [comment]
Superseded by #75

**Pull request closed without merging**
