### PR TITLE
Leave bucket management to the user.

### PR DESCRIPTION
**Pull request by j-bennet**
No default bucket, user should create the bucket before calling `to_gbq`.

Alternative to https://github.com/coiled/dask-bigquery/pull/61.

### CODE REVIEW

**Comment by j-bennet** [comment]
macOS build segfaults, but it did that before :(.

```
dask_bigquery/tests/test_core.py::test_arrow_options PASSED              [ 93%]
Fatal Python error: Segmentation fault

Thread 0x000070000ee82000 (most recent call first):
dask_bigquery/tests/test_core.py::test_read_required_partition_filter 
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.10/threading.py", line 953 in run
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.10/threading.py", line 973 in _bootstrap
```

**Comment by ncclementi** [comment]
We merged #61 do we still want this one ?

**Comment by j-bennet** [comment]
@ncclementi This one is up for discussion. It's "best practice" but less convenient to "I want to try" users, how much do we care?

**Comment by jrbourbeau** [comment]
Looks like we went with https://github.com/coiled/dask-bigquery/pull/61 -- should we close this PR then?

**Comment by j-bennet** [comment]
@jrbourbeau

> Looks like we went with #61 -- should we close this PR then?

That's what we need to talk about. :)

We went with #61 to fix a non-unique bucket problem, yes. But not managing those buckets at all is probably a better pattern. Do you have an opinion on it?

**Comment by j-bennet** [comment]
After chatting with @jrbourbeau, decided not to fix while it ain't broken.

**Pull request closed without merging**
